language: objective-c
osx_image: xcode7.1
script:
  - xcodebuild -scheme SwiftExample -workspace SwiftExample.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' build test
after_success:
  - bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/2476352d3ee3eb5c65795f9472b163ab0ac8933e/codecov)
