language: objective-c
osx_image: xcode7.3
script:
  - xcodebuild -scheme SwiftExample -workspace SwiftExample.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1' build test
  - find / -name '*.xccoverage'
  - find ~/Library/Developer/Xcode/DerivedData -name '*.xccoverage'
after_success:
  - bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/dbf2ec11c3cac2cf7a54f48a77ee6d7ab18043c1/codecov) -X xcode -X xcodeplist
